### PR TITLE
[WIP][RFC] D-Bus Interface Rewrite

### PR DESCRIPTION
**Pull request by AstraLuma**
So... yeah. I basically rewrote the entire thing. Broke up a bunch of stuff. Expanded implementations. The works.

I decided to go with asyncio for a few reasons: 1. Running as a D-Bus service means we're already event driven, 2. We can prevent problems in one part from blocking other parts, 3. I've got `aioevents` I've been meaning to use (Although it integrates with D-Bus signals so-so).

The things that still need to be done:
- Any generator that manages more than one block is not yet updated. The boilerplate hasn't been developed
- I want to rewrite output in a non-blocking manner
- Click events need to be parsed and forwarded to D-Bus
- gbulb is pretty much broken. I (or someone) needs to fork it.
- A pile of other FIXMEs and TODOs

At this point, it seems to work as well as it did when I forked it. This PR is for feedback and comments.

### CODE REVIEW

**Comment by acrisci** [comment]
I can't get it to work.

When I run a generator I get this

```
Traceback (most recent call last):
  File "./clock", line 3, in <module>
    from i3dstatus.utils import get_config, make_block
ImportError: No module named 'i3dstatus'
```

If I install and run a generator, I get this

```
Traceback (most recent call last):
  File "./generators/clipboard", line 5, in <module>
    from i3dstatus.utils import get_config, make_block
  File "/usr/lib/python3.4/site-packages/i3_dstatus-0.0.3-py3.4.egg/i3dstatus/__init__.py", line 9, in <module>
ImportError: No module named 'i3dstatus.gbulb'
```

**Comment by AstraLuma** [comment]
Oh, run `sudo python3 setup.py develop`. It "installs" your workspace into the Python path.

**Comment by acrisci** [comment]
There are some really good ideas here, but it's too hard to give a proper review of all the changes you made here, so I'll give a general outline of what I think of the direction you are taking. You should resubmit these changes in smaller pull requests organized in logical commits so it's easier to review (and on a feature branch as well).

My first impression is that we have taken a very simple interface (basically just a single method to show blocks) and turned it into a very complicated interface with no clear benefit. If you think this interface is better than the previous one, I'd like to hear why.

I like the idea of having the option of working with blocks as proxy objects. For this, there is a standard interface `org.freedesktop.DBus.Properties` which we should be using.

My vision for the project is to allow people to write very simple scripts to update the statusline, without having to know much about dbus, in any programming language. The single method is good for this because there are plenty of examples for calling a dbus method, and it allows for some cool things like a one-liner to update the statusline from the command line with external tools.

Another thing is that there is no good way to set the order with this approach. It seems like setting the order is left to each individual block, which I think makes it hard to configure the order.

I'd also like to keep the process management in the application. It makes it really easy to configure which generators run and in what order from a centralized place. The ability to specify this on the command line is nice because it eliminates the need for the configuration file all together.

**Comment by AstraLuma** [comment]
The `Block` interface is tedious, but not terribly complicated (Just a pile of getters and setters with a bulk update operation). The implementation is long simply because of the amount of boilerplate code required. Explore it with [D-Feet](https://wiki.gnome.org/action/show/Apps/DFeet) if you're getting lost in there.

Order is left as a number on the `Block`. D-Bus doesn't have a concept of object order, and I can't think of a simpler way to expose the order on the API. (Order doesn't have to be consecutive, and in fact I would encourage initial number of 10, 20, 30, .... so that other blocks can be inserted.) I can add utility methods for navigation and movement (next, previous, move after, move before, etc). I figure when I get around to actually doing stuff with the config file again, it can default the order. (Keep in mind, in order to definitively correlate a block to a process, we'd have to trace API calls back through d-bus. Possible, but probably tricky.)

Yup, implementing `org.freedesktop.DBus.Properties` is totally on my todo list. I just didn't realize it existed when I first went through `Block`. 

As for very simple interfaces, see some of the updated scripts ([clock](https://github.com/astronouth7303/i3-dstatus/blob/master/i3dstatus/generators/clock)). I found that to do things Right (block clean up, etc), it was easier to implement a [utility library](https://github.com/astronouth7303/i3-dstatus/blob/master/i3dstatus/utils.py).

As far as things like the one-liner, you can still update a block with one-line, as long as it already exists. 2-lines otherwise (create-or-ignore-error, update). If having a single magic search-and-update method is really that crucial, it's easy enough to add a convenience method.

As for process management, I nixed because it was a secondary feature not crucial to the core problem (Shuffling blocks from d-bus to i3bar, and getting events from i3bar to d-bus). It's something that can be tackled when the configuration file is properly sussed out, with real process management stuff (Restart on crash, logging stderr, ...). I just wanted it out of my way. (Counterpoint: i3 doesn't do real process management. Do we want to leave that out of this as well? Discussion for later.)

As always, you can find me on `#i3` if you want to debate some of the finer points.

**Comment by AstraLuma** [comment]
(Oh, getting the PID of a D-Bus name is `org.freedesktop.DBus.GetConnectionUnixProcessID`.)

**Comment by anithri** [comment]
My personal use of i3-dstatus is to use a mix of the included generators, and some that I wrote in ruby (anithri/i3-rbgen). I love the way I can mix generators of any language on the command line, and have them be started and restarted with i3-dstatus.  

l also think that any ordering of blocks should be done in the configuration file as explicitly as possible.    Expecting each block generator to calculate, or issue commands, to order themselves seems a recipe for hard to configure layouts.

**Comment by AstraLuma** [comment]
This round of commits nukes `get_*`/`set_*` in favor of `org.freedesktop.DBus.Properties` or (if you're lazy) generic `get`/`set`. This removes over 250 lines of code.

**Comment by acrisci** [comment]
I agree with @anithri that ordering should be possible within the configuration file or on the command line, and I also think that generators should be given the option to override the ordering with a property.

@astronouth7303 please start sending smaller pull requests so I can do a proper review for each change individually. I'm not going to merge a rewrite.

**Pull request closed without merging**
