### PR TITLE
Add home path

### PR DESCRIPTION
**Pull request by anithri**
Added ability to have both / and ~/ to specify external paths to generators of command line

### CODE REVIEW

**Comment by acrisci** [comment]
This is a good change, but you could potentially have a valid relative path that starts with `~` such as `~file`.

It would be better to call `os.path.expanduser()` on the path and check if that is an absolute path.

**Comment by anithri** [comment]
So more like this

**Comment by acrisci** [comment]
This still has the problem of treating `~file` as an absolute path.

I think the best way to go about this is something like this:

```
if !os.path.isabs(os.path.expanduser(generator))
    # the path is not absolute
```

**Comment by acrisci** [comment]
Thanks for the contribution. I might make a small style adjustment.

**Pull request merged**
