### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by AstraLuma**
Doing some break-up (Single-concern stuff) before the big rewrite.

### CODE REVIEW

**Comment by acrisci** [comment]
Other than that, it looks pretty good.

**Comment by AstraLuma** [comment]
This round of commits implemented the process "manager". It will run any program given to it on the command line and any program in `general.generators` in the config file.

The algorithm to find generators is as follows:
1. Check if it's an absolute path (after performing `~` expansions)
2. Check if it's one of the bundled generators
3. Assume it's on the `PATH`

**Comment by acrisci** [comment]
Generator ordering is completely broken. I can't find where it was broken, but it doesn't work anymore.

There are way too many breaking api changes here to justify calling this "refactoring". This is turning into another complete rewrite. This pull request is really hard to review.

**Comment by AstraLuma** [comment]
Generators don't have an order.

Block ordering is 100% unimplemented at this point in `apirewrite`. I'm trying to do things in smaller chunks so that I have less to go back and fix.

**Comment by acrisci** [comment]
Working with rewrite pull requests is a very bad way of doing things.

For one, it is really hard to review and discuss the changes unless it is organized into small incremental pull requests.

Another thing is that it ties up all the code so nobody else can contribute while the rewrite pull request is ongoing.

So now I need to add unit tests for the purpose of this pull request, but I can't do that without breaking your pull request.

**Comment by AstraLuma** [comment]
I'm not sure it's possible to avoid a rewrite with the work I'm trying to do. I can break it up into smaller pieces, but there's a lot of changes.

If you think the direction I'm trying to go in (explicit structured APIs at the D-Bus level with full CRUD) is the wrong one, then tell me now.

**Comment by acrisci** [comment]
Break it down into smaller pieces, and be prepared to justify the changes you are making.

For something like a complete redesign of the d-bus interface, you should be creating an issue where you detail the new interface and say why it is useful.

**Pull request closed without merging**
